## **一次捕获多个异常**

`IOError`可以捕获到`FileNotFoundError`

```python
try:
    f.open("no_exist.txt")
except (NameError, IOError):
    print('ERROR!')
```

## 显示异常的信息

```python
try:
    f.open("no_exist.txt")
except IOError as result:
    print('ERROR!')
    print(result)
```
## **捕获所有异常**

```python
try:
    f.open("no_exist.txt")
except Exception as e:
    print('ERROR!')
    print(e)
```
## **异常捕获嵌套**

如果把文件打开了，但是处理的过程中出现了错误，之后要保证把文件给关闭了。

```python
try:
    f.open("no_exist.txt")
    try: while True:
        content = f.readline()
        if len(content) == 0:
            break
        time.sleep(2)
        print(content)
    finally:
        f.close()
        print('文件关闭')

except Exception as e:
    print('ERROR!')
    print(e)
```

## 使用场景：判断输入是否正确

```python
try:
    age = int(input('请输入年龄'))
except Exception as e:
    print('输入的不是数字')
    print(e)
else:
    if int(age) > 18:
        print('欢迎')
    else:
        print('再见')
```

## finally注意事项

如果函数有finally，finally里的返回值会覆盖之前的返回值。

```python
try:
    x = a / b
except ZeroDivisionError:
    return '除数不能为0'
else:
    return x
finally:
    return 'good'  # 无论如何都会返回这一行
```

## 自定义异常

```
ZeroDivisonError
FileNotFoundError
FileExistsError  # 创建重名
ValueError
KeyError
SyntaxError
IndexError

```

解决异常不够用的问题

```python
class LengthError(Exception):
    def __init__(self, x, y):
        Exception.__init__(self)
        self.x = x
        self.y = y
    def __str__(self):
        return "长度必须在{}至{}之间".format(self.x, self.y)

password = input('请输入您的密码：')

m, n = 6, 12
if m <= len(password) <= n:
    print('密码正确')
else:
    raise LengthError(m, n)
    # raise ValueError('密码格式错误！')  # 系统自带错误
    # print('密码格式错误！')

# 密码保存到数据库    
print('密码保存到数据库')
```



